openapi: 3.0.0
info:
  title: API de S-MEC
  version: 1.0.0
  description: >-

    # Documentación de la API de SMEC


    Esta API permite la gestión integral de pacientes, consultas e informes para
    La SMEC.


    ## Características


    * **Pacientes**: Registro y consulta de información de pacientes.

    * **Laboratorio**: Registro y seguimiento de análisis laboratoriales.

    * **Informes**: Generación de reportes y estadísticas.


    ## Autenticación


    Todos los endpoints protegidos requieren autenticación mediante un token
    JWT.

    Para obtener un token, utiliza el [endpoint de
    login](#tag/Autenticacion/paths/~1login/post).


    ```

    Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9...

    ```


    ## Recursos adicionales


    * [Manual](https://example.com/manual)

    * [Guía de desarrollo](https://example.com/dev-guide)

    * [Contacto de soporte](mailto:soporte@smec.com)


    > **Nota importante**: Esta API está destinada únicamente para uso
    autorizado.

    > El acceso no autorizado está prohibido y será monitoreado.
                
  contact:
    name: Equipo de Desarrollo SMEC
    email: desarrollo@smec.com
    url: https://smec.com/contacto
servers:
  - url: http://localhost:52000
    description: Servidor local de desarrollo
paths:
  /v1/login:
    post:
      tags:
        - Autenticacion
      summary: Servicio de logueo
      description: Permite autenticar un usuario o renovar su refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: '111111'
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
                  id:
                    type: string
                  username:
                    type: string
                  nombre:
                    type: string
                  apellido:
                    type: string
                  usuarioActivo:
                    type: boolean
                  rolId:
                    type: integer
                  permisoEliminar:
                    type: boolean
                  menus:
                    type: array
                    items:
                      type: object
        '400':
          description: Falta un parámetro
        '401':
          description: Credencial incorrecta
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags: []
