openapi: 3.0.0
info:
  title: API de S-MEC
  version: 1.0.0
  description: >-

    # Documentación de la API de SMEC


    Esta API permite la gestión integral de pacientes, consultas e informes para
    La SMEC.


    ## Características


    * **Pacientes**: Registro y consulta de información de pacientes.

    * **Laboratorio**: Registro y seguimiento de análisis laboratoriales.

    * **Informes**: Generación de reportes y estadísticas.


    ## Autenticación


    Todos los endpoints protegidos requieren autenticación mediante un token
    JWT.

    Para obtener un token, utiliza el [endpoint de
    login](#tag/Autenticacion/paths/~1login/post).


    ```

    Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9...

    ```


    ## Recursos adicionales


    * [Manual](https://example.com/manual)

    * [Guía de desarrollo](https://example.com/dev-guide)

    * [Contacto de soporte](mailto:soporte@smec.com)


    > **Nota importante**: Esta API está destinada únicamente para uso
    autorizado.

    > El acceso no autorizado está prohibido y será monitoreado.
                
  contact:
    name: Equipo de Desarrollo SMEC
    email: desarrollo@smec.com
    url: https://smec.com/contacto
servers:
  - url: http://localhost:52000
    description: Servidor local de desarrollo
paths:
  /v1/login:
    post:
      tags:
        - Autenticacion
      summary: Servicio de logueo
      description: Permite autenticar un usuario o renovar su refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  example: '111111'
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  token:
                    type: string
                  id:
                    type: string
                  username:
                    type: string
                  nombre:
                    type: string
                  apellido:
                    type: string
                  usuarioActivo:
                    type: boolean
                  rolId:
                    type: integer
                  permisoEliminar:
                    type: boolean
                  menus:
                    type: array
                    items:
                      type: object
        '400':
          description: Falta un parámetro
        '401':
          description: Credencial incorrecta
  /v1/persona/agendamiento:
    post:
      summary: Servicio de registro de personas con agendamiento
      tags:
        - Persona
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - cedula
                - nombre
                - apellido
                - fechaNacimiento
                - perfilId
                - ubicacionId
                - plantaTrabajoId
                - empresaId
                - fechaAgendamiento
                - puestoTrabajo
                - sexoId
                - realizaElectrocardiograma
                - realizaRadiografia
              properties:
                cedula:
                  type: string
                  example: "3391416"
                nombre:
                  type: string
                  example: "Rodrigo"
                apellido:
                  type: string
                  example: "Santos"
                fechaNacimiento:
                  type: string
                  format: date
                  example: "1991-08-21"
                perfilId:
                  type: integer
                  example: 1
                ubicacionId:
                  type: integer
                  example: 1
                plantaTrabajoId:
                  type: integer
                  example: 1
                empresaId:
                  type: integer
                  example: 1
                fechaAgendamiento:
                  type: string
                  format: date
                  example: "2025-01-15"
                puestoTrabajo:
                  type: string
                  example: "Cocina"
                sexoId:
                  type: string
                  example: "1"
                realizaElectrocardiograma:
                  type: boolean
                  example: true
                realizaRadiografia:
                  type: boolean
                  example: false
      responses:
        '200':
          description: Persona registrada exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  personaId:
                    type: integer
                    example: 1
        '400':
          description: Falta un parámetro
        '401':
          description: Credencial incorrecta
  /v1/publico/perfil:
    get:
      summary: Listar perfiles
      tags:
        - Público
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de perfiles obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: Admisional
              example:
                - id: 1
                  nombre: Admisional
                - id: 2
                  nombre: Periodico
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
  /v1/persona/agendamiento/list:
    post:
      summary: Listar personas agendadas (paginado)
      tags:
        - Persona
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filtro:
                  type: string
                  example: ""
                estadoId:
                  type: integer
                  example: 1
                fechaAgendamiento:
                  type: string
                  format: date
                  example: "2025-01-13"
                pagina:
                  type: string
                  example: "1"
                porPagina:
                  type: string
                  example: "10"
      responses:
        '200':
          description: Lista paginada de personas agendadas
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        cedula:
                          type: string
                        nombre:
                          type: string
                        apellido:
                          type: string
                        fechaNacimiento:
                          type: string
                          format: date
                        edad:
                          type: integer
                        puestoTrabajo:
                          type: string
                        sexoId:
                          type: string
                        realizaElectrocardiograma:
                          type: boolean
                        realizaRadiografia:
                          type: boolean
                        perfil:
                          type: object
                          properties:
                            id:
                              type: integer
                            nombre:
                              type: string
                        ubicacion:
                          type: object
                          properties:
                            id:
                              type: integer
                            nombre:
                              type: string
                        plantaTrabajo:
                          type: object
                          properties:
                            id:
                              type: integer
                            nombre:
                              type: string
                        empresa:
                          type: object
                          properties:
                            id:
                              type: integer
                            nombre:
                              type: string
                        estado:
                          type: object
                          properties:
                            id:
                              type: integer
                            nombre:
                              type: string
                        fechaAgendamiento:
                          type: string
                          format: date
                        agendadoPor:
                          type: string
                        recepcion:
                          type: object
                          properties:
                            entregoMuestraOrina:
                              type: boolean
                            entregoMuestraHaces:
                              type: boolean
                            fechaRecepcion:
                              type: string
                            usuarioRecepcion:
                              type: string
                            extraccionSangre:
                              type: boolean
                            fechaExtraccion:
                              type: string
                            usuarioExtraccion:
                              type: integer
                        consulta:
                          type: object
                          properties:
                            electrocardiogramaRealizado:
                              type: boolean
                            habitos:
                              type: object
                              properties:
                                fuma:
                                  type: integer
                            patologicoFamiliar:
                              type: object
                            patologicoPersonal:
                              type: object
                            examenFisico:
                              type: object
                            fechaConsulta:
                              type: string
                            usuarioConsulta:
                              type: string
                        electrocardiograma:
                          type: object
                          properties:
                            electrocardiogramaRealizado:
                              type: boolean
                            fechaElectrocardiograma:
                              type: string
                            usuarioElectrocardiograma:
                              type: integer
                        radiografia:
                          type: object
                          properties:
                            radiografia:
                              type: boolean
                            fechaRadiografia:
                              type: string
                            usuarioRadiografia:
                              type: integer
                  pagination:
                    type: object
                    properties:
                      actual:
                        type: string
                      cantidad:
                        type: string
                      porPagina:
                        type: string
                      total:
                        type: integer
                  message:
                    type: string
                  success:
                    type: boolean
        '400':
          description: Falta un parámetro
        '401':
          description: Credencial incorrecta
  /v1/publico/sucursal:
    get:
      summary: Servicio de listar sucursales
      description: Listar sucursales
      tags:
        - Público
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de sucursales obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    entidadId:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: "Ubicacion 1"
                    nroSucursal:
                      type: integer
                      example: 1
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
  /v1/persona/{id}/agendamiento/informes:
    post:
      summary: Servicio para recuperar informes de la persona
      description: Servicio para recuperar informes de la persona
      tags:
        - Persona
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la persona_agendamiento
          schema:
            type: integer
            example: 123
      responses:
        '200':
          description: Informes recuperados correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  informeManipulacion:
                    type: string
                    format: uri
                    example: "www.informe.com.py"
                  informeApto:
                    type: string
                    format: uri
                    example: "www.informe.com.py"
                  informeFichaPaciente:
                    type: string
                    format: uri
                    example: "www.informe.com.py"
                  archivoAdjunto1:
                    type: string
                    format: uri
                    example: "www.informe.com.py"
                  archivoAdjunto2:
                    type: string
                    format: uri
                    example: "www.informe.com.py"
                  archivoAdjunto3:
                    type: string
                    format: uri
                    example: "www.informe.com.py"
        '400':
          description: Falta un parámetro
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Falta un parámetro
        '401':
          description: Credencial incorrecta
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Credencial incorrecta
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags: []
